const regionDefinitions = [
  { name: '香港', flag: '🇭🇰', regex: new RegExp('🇭🇰|香港|\\bHKG?\\b|hong[\\s_-]*kong', 'i'), icon: '' },
  {
    name: '台湾',
    flag: '🇹🇼',
    regex: new RegExp('🇹🇼|台湾|台北|高雄|新北|桃园|新竹|\\bTWN?\\b|taiwan|taipei|hinet', 'i'),
    icon: '',
  },
  { name: '日本', flag: '🇯🇵', regex: new RegExp('🇯🇵|日本|\\bJPN?\\b|japan|tokyo|osaka|东京|大阪', 'i'), icon: '' },
  {
    name: '韩国',
    flag: '🇰🇷',
    regex: new RegExp('🇰🇷|韩国|(?:^|[^A-Za-z])KR(?:$|[^A-Za-z])|korea|seoul|首尔', 'i'),
    icon: '',
  },
  { name: '新加坡', flag: '🇸🇬', regex: new RegExp('🇸🇬|新加坡|狮城|\\bSGP?\\b|singapore', 'i'), icon: '' },
  {
    name: '美国',
    flag: '🇺🇸',
    regex: new RegExp(
      '🇺🇸|美国|(?:^|[^A-Za-z])US(?:$|[^A-Za-z])|(?:^|[^A-Za-z])USA(?:$|[^A-Za-z])|america|united[\\s_-]*states|los[\\s_-]*angeles|洛杉矶|san[\\s_-]*jose|圣何塞|纽约|new[\\s_-]*york|芝加哥|chicago|达拉斯|dallas|西雅图|seattle|硅谷|矽谷|silicon|迈阿密|miami|凤凰城|phoenix',
      'i',
    ),
    icon: '',
  },
  {
    name: '英国',
    flag: '🇬🇧',
    regex: new RegExp('🇬🇧|英国|(?:^|[^A-Za-z0-9])GB(?:$|[^A-Za-z])|united[\\s_-]*kingdom|london|伦敦', 'i'),
    icon: '',
  },
  {
    name: '德国',
    flag: '🇩🇪',
    regex: new RegExp('🇩🇪|德国|(?:^|[^A-Za-z])DE(?:$|[^A-Za-z])|germany|frankfurt|法兰克福', 'i'),
    icon: '',
  },
  {
    name: '荷兰',
    flag: '🇳🇱',
    regex: new RegExp('🇳🇱|荷兰|(?:^|[^A-Za-z])NL(?:$|[^A-Za-z])|nether?lands|amsterdam|阿姆斯特丹', 'i'),
    icon: '',
  },
  {
    name: '马来西亚',
    flag: '🇲🇾',
    regex: new RegExp('🇲🇾|马来西亚|(?:^|[^A-Za-z])MY(?:$|[^A-Za-z])|malaysia|kuala[\\s_-]*lumpur|吉隆坡', 'i'),
    icon: '',
  },
  {
    name: '泰国',
    flag: '🇹🇭',
    regex: new RegExp('🇹🇭|泰国|(?:^|[^A-Za-z])TH(?:$|[^A-Za-z])|thailand|bangkok|曼谷', 'i'),
    icon: '',
  },
  {
    name: '越南',
    flag: '🇻🇳',
    regex: new RegExp(
      '🇻🇳|越南|(?:^|[^A-Za-z])VN(?:$|[^A-Za-z])|vietnam|hanoi|河内|ho[\\s_-]*chi[\\s_-]*minh|胡志明',
      'i',
    ),
    icon: '',
  },
  {
    name: '菲律宾',
    flag: '🇵🇭',
    regex: new RegExp('🇵🇭|菲律宾|(?:^|[^A-Za-z])PH(?:$|[^A-Za-z])|philippines|manila|马尼拉', 'i'),
    icon: '',
  },
  {
    name: '印尼',
    flag: '🇮🇩',
    regex: new RegExp('🇮🇩|印尼|印度尼西亚|(?:^|[^A-Za-z])ID(?:$|[^A-Za-z])|indonesia|jakarta|雅加达', 'i'),
    icon: '',
  },
  {
    name: '印度',
    flag: '🇮🇳',
    regex: new RegExp('🇮🇳|印度|(?:^|[^A-Za-z])IN(?:$|[^A-Za-z])|india|mumbai|孟买|delhi|德里', 'i'),
    icon: '',
  },
  {
    name: '澳大利亚',
    flag: '🇦🇺',
    regex: new RegExp('🇦🇺|澳大利亚|澳洲|(?:^|[^A-Za-z])AU(?:$|[^A-Za-z])|australia|sydney|悉尼|melbourne|墨尔本', 'i'),
    icon: '',
  },
  {
    name: '法国',
    flag: '🇫🇷',
    regex: new RegExp('🇫🇷|法国|(?:^|[^A-Za-z])FR(?:$|[^A-Za-z])|france|paris|巴黎', 'i'),
    icon: '',
  },
  {
    name: '俄罗斯',
    flag: '🇷🇺',
    regex: new RegExp('🇷🇺|俄罗斯|(?:^|[^A-Za-z])RU(?:$|[^A-Za-z])|russia|moscow|莫斯科', 'i'),
    icon: '',
  },
  {
    name: '意大利',
    flag: '🇮🇹',
    regex: new RegExp('🇮🇹|意大利|(?:^|[^A-Za-z])IT(?:$|[^A-Za-z])|\\bitaly\\b|rome|罗马', 'i'),
    icon: '',
  },
  {
    name: '加拿大',
    flag: '🇨🇦',
    regex: new RegExp('🇨🇦|加拿大|(?:^|[^A-Za-z])CA(?:$|[^A-Za-z])|canada|toronto|多伦多', 'i'),
    icon: '',
  },
  {
    name: '阿根廷',
    flag: '🇦🇷',
    regex: new RegExp('🇦🇷|阿根廷|(?:^|[^A-Za-z])AR(?:$|[^A-Za-z])|argentina|buenos[\\s_-]*aires|布宜诺斯艾利斯', 'i'),
    icon: '',
  },
  {
    name: '巴西',
    flag: '🇧🇷',
    regex: new RegExp('🇧🇷|巴西|(?:^|[^A-Za-z])BR(?:$|[^A-Za-z])|brazil|sao[\\s_-]*paulo|圣保罗', 'i'),
    icon: '',
  },
  { name: '墨西哥', flag: '🇲🇽', regex: new RegExp('🇲🇽|墨西哥|(?:^|[^A-Za-z])MX(?:$|[^A-Za-z])|mexico', 'i'), icon: '' },
  {
    name: '沙特阿拉伯',
    flag: '🇸🇦',
    regex: new RegExp('🇸🇦|沙特阿拉伯|沙特|(?:^|[^A-Za-z])SA(?:$|[^A-Za-z])|saudi[\\s_-]*arabia', 'i'),
    icon: '',
  },
  {
    name: '南非',
    flag: '🇿🇦',
    regex: new RegExp('🇿🇦|南非|(?:^|[^A-Za-z])ZA(?:$|[^A-Za-z])|south[\\s_-]*africa|johannesburg|约翰内斯堡', 'i'),
    icon: '',
  },
  {
    name: '土耳其',
    flag: '🇹🇷',
    regex: new RegExp('🇹🇷|土耳其|(?:^|[^A-Za-z])TR(?:$|[^A-Za-z])|turkey|istanbul|伊斯坦布尔', 'i'),
    icon: '',
  },
  { name: '文莱', flag: '🇧🇳', regex: new RegExp('🇧🇳|文莱|(?:^|[^A-Za-z])BN(?:$|[^A-Za-z])|brunei', 'i'), icon: '' },
  {
    name: '柬埔寨',
    flag: '🇰🇭',
    regex: new RegExp('🇰🇭|柬埔寨|(?:^|[^A-Za-z])KH(?:$|[^A-Za-z])|cambodia|phnom[\\s_-]*penh|金边', 'i'),
    icon: '',
  },
  {
    name: '老挝',
    flag: '🇱🇦',
    regex: new RegExp('🇱🇦|老挝|(?:^|[^A-Za-z])LA(?:$|[^A-Za-z])|\\blaos\\b|vientiane|万象', 'i'),
    icon: '',
  },
  {
    name: '缅甸',
    flag: '🇲🇲',
    regex: new RegExp('🇲🇲|缅甸|(?:^|[^A-Za-z])MM(?:$|[^A-Za-z])|myanmar|yangon|仰光', 'i'),
    icon: '',
  },
  {
    name: '奥地利',
    flag: '🇦🇹',
    regex: new RegExp('🇦🇹|奥地利|(?:^|[^A-Za-z])AT(?:$|[^A-Za-z])|austria|vienna|维也纳', 'i'),
    icon: '',
  },
  {
    name: '比利时',
    flag: '🇧🇪',
    regex: new RegExp('🇧🇪|比利时|(?:^|[^A-Za-z])BE(?:$|[^A-Za-z])|belgium|brussels|布鲁塞尔', 'i'),
    icon: '',
  },
  {
    name: '保加利亚',
    flag: '🇧🇬',
    regex: new RegExp('🇧🇬|保加利亚|(?:^|[^A-Za-z])BG(?:$|[^A-Za-z])|bulgaria|sofia|索非亚', 'i'),
    icon: '',
  },
  {
    name: '克罗地亚',
    flag: '🇭🇷',
    regex: new RegExp('🇭🇷|克罗地亚|(?:^|[^A-Za-z])HR(?:$|[^A-Za-z])|croatia', 'i'),
    icon: '',
  },
  {
    name: '塞浦路斯',
    flag: '🇨🇾',
    regex: new RegExp('🇨🇾|塞浦路斯|(?:^|[^A-Za-z])CY(?:$|[^A-Za-z])|cyprus', 'i'),
    icon: '',
  },
  {
    name: '捷克',
    flag: '🇨🇿',
    regex: new RegExp('🇨🇿|捷克|捷克共和国|(?:^|[^A-Za-z])CZ(?:$|[^A-Za-z])|czech|prague|布拉格', 'i'),
    icon: '',
  },
  {
    name: '丹麦',
    flag: '🇩🇰',
    regex: new RegExp('🇩🇰|丹麦|(?:^|[^A-Za-z])DK(?:$|[^A-Za-z])|denmark|copenhagen|哥本哈根', 'i'),
    icon: '',
  },
  {
    name: '爱沙尼亚',
    flag: '🇪🇪',
    regex: new RegExp('🇪🇪|爱沙尼亚|(?:^|[^A-Za-z])EE(?:$|[^A-Za-z])|estonia', 'i'),
    icon: '',
  },
  {
    name: '芬兰',
    flag: '🇫🇮',
    regex: new RegExp('🇫🇮|芬兰|(?:^|[^A-Za-z])FI(?:$|[^A-Za-z])|finland|helsinki|赫尔辛基', 'i'),
    icon: '',
  },
  {
    name: '希腊',
    flag: '🇬🇷',
    regex: new RegExp('🇬🇷|希腊|(?:^|[^A-Za-z])GR(?:$|[^A-Za-z])|greece|athens|雅典', 'i'),
    icon: '',
  },
  {
    name: '匈牙利',
    flag: '🇭🇺',
    regex: new RegExp('🇭🇺|匈牙利|(?:^|[^A-Za-z])HU(?:$|[^A-Za-z])|hungary|budapest|布达佩斯', 'i'),
    icon: '',
  },
  {
    name: '爱尔兰',
    flag: '🇮🇪',
    regex: new RegExp('🇮🇪|爱尔兰|(?:^|[^A-Za-z])IE(?:$|[^A-Za-z])|ireland|dublin|都柏林', 'i'),
    icon: '',
  },
  {
    name: '拉脱维亚',
    flag: '🇱🇻',
    regex: new RegExp('🇱🇻|拉脱维亚|(?:^|[^A-Za-z])LV(?:$|[^A-Za-z])|latvia', 'i'),
    icon: '',
  },
  {
    name: '立陶宛',
    flag: '🇱🇹',
    regex: new RegExp('🇱🇹|立陶宛|(?:^|[^A-Za-z])LT(?:$|[^A-Za-z])|lithuania', 'i'),
    icon: '',
  },
  {
    name: '卢森堡',
    flag: '🇱🇺',
    regex: new RegExp('🇱🇺|卢森堡|(?:^|[^A-Za-z])LU(?:$|[^A-Za-z])|luxembourg', 'i'),
    icon: '',
  },
  { name: '马耳他', flag: '🇲🇹', regex: new RegExp('🇲🇹|马耳他|(?:^|[^A-Za-z])MT(?:$|[^A-Za-z])|malta', 'i'), icon: '' },
  {
    name: '波兰',
    flag: '🇵🇱',
    regex: new RegExp('🇵🇱|波兰|(?:^|[^A-Za-z])PL(?:$|[^A-Za-z])|poland|warsaw|华沙', 'i'),
    icon: '',
  },
  {
    name: '葡萄牙',
    flag: '🇵🇹',
    regex: new RegExp('🇵🇹|葡萄牙|(?:^|[^A-Za-z])PT(?:$|[^A-Za-z])|portugal|lisbon|里斯本', 'i'),
    icon: '',
  },
  {
    name: '罗马尼亚',
    flag: '🇷🇴',
    regex: new RegExp('🇷🇴|罗马尼亚|(?:^|[^A-Za-z])RO(?:$|[^A-Za-z])|romania|bucharest|布加勒斯特', 'i'),
    icon: '',
  },
  {
    name: '斯洛伐克',
    flag: '🇸🇰',
    regex: new RegExp('🇸🇰|斯洛伐克|(?:^|[^A-Za-z])SK(?:$|[^A-Za-z])|slovakia', 'i'),
    icon: '',
  },
  {
    name: '斯洛文尼亚',
    flag: '🇸🇮',
    regex: new RegExp('🇸🇮|斯洛文尼亚|(?:^|[^A-Za-z])SI(?:$|[^A-Za-z])|slovenia', 'i'),
    icon: '',
  },
  {
    name: '西班牙',
    flag: '🇪🇸',
    regex: new RegExp('🇪🇸|西班牙|(?:^|[^A-Za-z])ES(?:$|[^A-Za-z])|\\bspain\\b|madrid|马德里', 'i'),
    icon: '',
  },
  {
    name: '瑞典',
    flag: '🇸🇪',
    regex: new RegExp('🇸🇪|瑞典|(?:^|[^A-Za-z])SE(?:$|[^A-Za-z])|sweden|stockholm|斯德哥尔摩', 'i'),
    icon: '',
  },
  {
    name: '阿尔及利亚',
    flag: '🇩🇿',
    regex: new RegExp('🇩🇿|阿尔及利亚|(?:^|[^A-Za-z])DZ(?:$|[^A-Za-z])|algeria', 'i'),
    icon: '',
  },
  { name: '安哥拉', flag: '🇦🇴', regex: new RegExp('🇦🇴|安哥拉|(?:^|[^A-Za-z])AO(?:$|[^A-Za-z])|angola', 'i'), icon: '' },
  { name: '贝宁', flag: '🇧🇯', regex: new RegExp('🇧🇯|贝宁|(?:^|[^A-Za-z])BJ(?:$|[^A-Za-z])|benin', 'i'), icon: '' },
  {
    name: '博茨瓦纳',
    flag: '🇧🇼',
    regex: new RegExp('🇧🇼|博茨瓦纳|(?:^|[^A-Za-z])BW(?:$|[^A-Za-z])|botswana', 'i'),
    icon: '',
  },
  {
    name: '布基纳法索',
    flag: '🇧🇫',
    regex: new RegExp('🇧🇫|布基纳法索|(?:^|[^A-Za-z])BF(?:$|[^A-Za-z])|burkina[\\s_-]*faso', 'i'),
    icon: '',
  },
  {
    name: '布隆迪',
    flag: '🇧🇮',
    regex: new RegExp('🇧🇮|布隆迪|(?:^|[^A-Za-z])BI(?:$|[^A-Za-z])|burundi', 'i'),
    icon: '',
  },
  {
    name: '佛得角',
    flag: '🇨🇻',
    regex: new RegExp('🇨🇻|佛得角|(?:^|[^A-Za-z])CV(?:$|[^A-Za-z])|cabo[\\s_-]*verde|cape[\\s_-]*verde', 'i'),
    icon: '',
  },
  {
    name: '喀麦隆',
    flag: '🇨🇲',
    regex: new RegExp('🇨🇲|喀麦隆|(?:^|[^A-Za-z])CM(?:$|[^A-Za-z])|cameroon', 'i'),
    icon: '',
  },
  {
    name: '中非共和国',
    flag: '🇨🇫',
    regex: new RegExp('🇨🇫|中非共和国|中非|(?:^|[^A-Za-z])CF(?:$|[^A-Za-z])|central[\\s_-]*african', 'i'),
    icon: '',
  },
  { name: '乍得', flag: '🇹🇩', regex: new RegExp('🇹🇩|乍得|(?:^|[^A-Za-z])TD(?:$|[^A-Za-z])|\\bchad\\b', 'i'), icon: '' },
  {
    name: '科摩罗',
    flag: '🇰🇲',
    regex: new RegExp('🇰🇲|科摩罗|(?:^|[^A-Za-z])KM(?:$|[^A-Za-z])|comoros', 'i'),
    icon: '',
  },
  {
    name: '刚果共和国',
    flag: '🇨🇬',
    regex: new RegExp('🇨🇬|刚果共和国|刚果（布）|(?:^|[^A-Za-z])CG(?:$|[^A-Za-z])|\\bcongo\\b', 'i'),
    icon: '',
  },
  {
    name: '刚果民主共和国',
    flag: '🇨🇩',
    regex: new RegExp(
      '🇨🇩|刚果民主共和国|刚果（金）|民主刚果|(?:^|[^A-Za-z])CD(?:$|[^A-Za-z])|dr[\\s_-]*congo|democratic[\\s_-]*republic[\\s_-]*of[\\s_-]*the[\\s_-]*congo',
      'i',
    ),
    icon: '',
  },
  {
    name: '科特迪瓦',
    flag: '🇨🇮',
    regex: new RegExp(
      '🇨🇮|科特迪瓦|象牙海岸|(?:^|[^A-Za-z])CI(?:$|[^A-Za-z])|cote[\\s_-]*d.ivoire|ivory[\\s_-]*coast',
      'i',
    ),
    icon: '',
  },
  {
    name: '吉布提',
    flag: '🇩🇯',
    regex: new RegExp('🇩🇯|吉布提|(?:^|[^A-Za-z])DJ(?:$|[^A-Za-z])|djibouti', 'i'),
    icon: '',
  },
  {
    name: '埃及',
    flag: '🇪🇬',
    regex: new RegExp('🇪🇬|埃及|(?:^|[^A-Za-z])EG(?:$|[^A-Za-z])|egypt|cairo|开罗', 'i'),
    icon: '',
  },
  {
    name: '赤道几内亚',
    flag: '🇬🇶',
    regex: new RegExp('🇬🇶|赤道几内亚|(?:^|[^A-Za-z])GQ(?:$|[^A-Za-z])|equatorial[\\s_-]*guinea', 'i'),
    icon: '',
  },
  {
    name: '厄立特里亚',
    flag: '🇪🇷',
    regex: new RegExp('🇪🇷|厄立特里亚|(?:^|[^A-Za-z])ER(?:$|[^A-Za-z])|eritrea', 'i'),
    icon: '',
  },
  {
    name: '斯威士兰',
    flag: '🇸🇿',
    regex: new RegExp('🇸🇿|斯威士兰|埃斯瓦蒂尼|(?:^|[^A-Za-z])SZ(?:$|[^A-Za-z])|eswatini|swaziland', 'i'),
    icon: '',
  },
  {
    name: '埃塞俄比亚',
    flag: '🇪🇹',
    regex: new RegExp('🇪🇹|埃塞俄比亚|(?:^|[^A-Za-z])ET(?:$|[^A-Za-z])|ethiopia', 'i'),
    icon: '',
  },
  {
    name: '加蓬',
    flag: '🇬🇦',
    regex: new RegExp('🇬🇦|加蓬|(?:^|[^A-Za-z])GA(?:$|[^A-Za-z])|\\bgabon\\b', 'i'),
    icon: '',
  },
  { name: '冈比亚', flag: '🇬🇲', regex: new RegExp('🇬🇲|冈比亚|(?:^|[^A-Za-z])GM(?:$|[^A-Za-z])|gambia', 'i'), icon: '' },
  {
    name: '加纳',
    flag: '🇬🇭',
    regex: new RegExp('🇬🇭|加纳|(?:^|[^A-Za-z])GH(?:$|[^A-Za-z])|\\bghana\\b', 'i'),
    icon: '',
  },
  {
    name: '几内亚',
    flag: '🇬🇳',
    regex: new RegExp('🇬🇳|几内亚|(?:^|[^A-Za-z])GN(?:$|[^A-Za-z])|\\bguinea\\b', 'i'),
    icon: '',
  },
  {
    name: '几内亚比绍',
    flag: '🇬🇼',
    regex: new RegExp('🇬🇼|几内亚比绍|(?:^|[^A-Za-z])GW(?:$|[^A-Za-z])|guinea-bissau|guinea[\\s_-]*bissau', 'i'),
    icon: '',
  },
  {
    name: '肯尼亚',
    flag: '🇰🇪',
    regex: new RegExp('🇰🇪|肯尼亚|(?:^|[^A-Za-z])KE(?:$|[^A-Za-z])|kenya|nairobi|内罗毕', 'i'),
    icon: '',
  },
  {
    name: '莱索托',
    flag: '🇱🇸',
    regex: new RegExp('🇱🇸|莱索托|(?:^|[^A-Za-z])LS(?:$|[^A-Za-z])|lesotho', 'i'),
    icon: '',
  },
  {
    name: '利比里亚',
    flag: '🇱🇷',
    regex: new RegExp('🇱🇷|利比里亚|(?:^|[^A-Za-z])LR(?:$|[^A-Za-z])|liberia', 'i'),
    icon: '',
  },
  {
    name: '利比亚',
    flag: '🇱🇾',
    regex: new RegExp('🇱🇾|利比亚|(?:^|[^A-Za-z])LY(?:$|[^A-Za-z])|\\blibya\\b', 'i'),
    icon: '',
  },
  {
    name: '马达加斯加',
    flag: '🇲🇬',
    regex: new RegExp('🇲🇬|马达加斯加|(?:^|[^A-Za-z])MG(?:$|[^A-Za-z])|madagascar', 'i'),
    icon: '',
  },
  { name: '马拉维', flag: '🇲🇼', regex: new RegExp('🇲🇼|马拉维|(?:^|[^A-Za-z])MW(?:$|[^A-Za-z])|malawi', 'i'), icon: '' },
  { name: '马里', flag: '🇲🇱', regex: new RegExp('🇲🇱|马里|(?:^|[^A-Za-z])ML(?:$|[^A-Za-z])|\\bmali\\b', 'i'), icon: '' },
  {
    name: '毛里塔尼亚',
    flag: '🇲🇷',
    regex: new RegExp('🇲🇷|毛里塔尼亚|(?:^|[^A-Za-z])MR(?:$|[^A-Za-z])|mauritania', 'i'),
    icon: '',
  },
  {
    name: '毛里求斯',
    flag: '🇲🇺',
    regex: new RegExp('🇲🇺|毛里求斯|(?:^|[^A-Za-z])MU(?:$|[^A-Za-z])|mauritius', 'i'),
    icon: '',
  },
  {
    name: '摩洛哥',
    flag: '🇲🇦',
    regex: new RegExp('🇲🇦|摩洛哥|(?:^|[^A-Za-z])MA(?:$|[^A-Za-z])|morocco|casablanca|卡萨布兰卡', 'i'),
    icon: '',
  },
  {
    name: '莫桑比克',
    flag: '🇲🇿',
    regex: new RegExp('🇲🇿|莫桑比克|(?:^|[^A-Za-z])MZ(?:$|[^A-Za-z])|mozambique', 'i'),
    icon: '',
  },
  {
    name: '纳米比亚',
    flag: '🇳🇦',
    regex: new RegExp('🇳🇦|纳米比亚|(?:^|[^A-Za-z])NA(?:$|[^A-Za-z])|\\bnamibia\\b', 'i'),
    icon: '',
  },
  {
    name: '尼日尔',
    flag: '🇳🇪',
    regex: new RegExp('🇳🇪|尼日尔|(?:^|[^A-Za-z])NE(?:$|[^A-Za-z])|\\bniger\\b', 'i'),
    icon: '',
  },
  {
    name: '尼日利亚',
    flag: '🇳🇬',
    regex: new RegExp('🇳🇬|尼日利亚|(?:^|[^A-Za-z])NG(?:$|[^A-Za-z])|nigeria|lagos|拉各斯', 'i'),
    icon: '',
  },
  { name: '卢旺达', flag: '🇷🇼', regex: new RegExp('🇷🇼|卢旺达|(?:^|[^A-Za-z])RW(?:$|[^A-Za-z])|rwanda', 'i'), icon: '' },
  {
    name: '圣多美和普林西比',
    flag: '🇸🇹',
    regex: new RegExp('🇸🇹|圣多美和普林西比|(?:^|[^A-Za-z])ST(?:$|[^A-Za-z])|sao[\\s_-]*tome', 'i'),
    icon: '',
  },
  {
    name: '塞内加尔',
    flag: '🇸🇳',
    regex: new RegExp('🇸🇳|塞内加尔|(?:^|[^A-Za-z])SN(?:$|[^A-Za-z])|senegal', 'i'),
    icon: '',
  },
  {
    name: '塞舌尔',
    flag: '🇸🇨',
    regex: new RegExp('🇸🇨|塞舌尔|(?:^|[^A-Za-z])SC(?:$|[^A-Za-z])|seychelles', 'i'),
    icon: '',
  },
  {
    name: '塞拉利昂',
    flag: '🇸🇱',
    regex: new RegExp('🇸🇱|塞拉利昂|(?:^|[^A-Za-z])SL(?:$|[^A-Za-z])|sierra[\\s_-]*leone', 'i'),
    icon: '',
  },
  {
    name: '索马里',
    flag: '🇸🇴',
    regex: new RegExp('🇸🇴|索马里|(?:^|[^A-Za-z])SO(?:$|[^A-Za-z])|somalia', 'i'),
    icon: '',
  },
  {
    name: '南苏丹',
    flag: '🇸🇸',
    regex: new RegExp('🇸🇸|南苏丹|(?:^|[^A-Za-z])SS(?:$|[^A-Za-z])|south[\\s_-]*sudan', 'i'),
    icon: '',
  },
  {
    name: '苏丹',
    flag: '🇸🇩',
    regex: new RegExp('🇸🇩|苏丹|(?:^|[^A-Za-z])SD(?:$|[^A-Za-z])|\\bsudan\\b', 'i'),
    icon: '',
  },
  {
    name: '坦桑尼亚',
    flag: '🇹🇿',
    regex: new RegExp('🇹🇿|坦桑尼亚|(?:^|[^A-Za-z])TZ(?:$|[^A-Za-z])|tanzania', 'i'),
    icon: '',
  },
  { name: '多哥', flag: '🇹🇬', regex: new RegExp('🇹🇬|多哥|(?:^|[^A-Za-z])TG(?:$|[^A-Za-z])|\\btogo\\b', 'i'), icon: '' },
  {
    name: '突尼斯',
    flag: '🇹🇳',
    regex: new RegExp('🇹🇳|突尼斯|(?:^|[^A-Za-z])TN(?:$|[^A-Za-z])|tunisia', 'i'),
    icon: '',
  },
  { name: '乌干达', flag: '🇺🇬', regex: new RegExp('🇺🇬|乌干达|(?:^|[^A-Za-z])UG(?:$|[^A-Za-z])|uganda', 'i'), icon: '' },
  { name: '赞比亚', flag: '🇿🇲', regex: new RegExp('🇿🇲|赞比亚|(?:^|[^A-Za-z])ZM(?:$|[^A-Za-z])|zambia', 'i'), icon: '' },
  {
    name: '津巴布韦',
    flag: '🇿🇼',
    regex: new RegExp('🇿🇼|津巴布韦|(?:^|[^A-Za-z])ZW(?:$|[^A-Za-z])|zimbabwe', 'i'),
    icon: '',
  },
  { name: '阿富汗', flag: '🇦🇫', regex: new RegExp('🇦🇫|阿富汗|afghanistan', 'i'), icon: '' },
  { name: '亚美尼亚', flag: '🇦🇲', regex: new RegExp('🇦🇲|亚美尼亚|armenia', 'i'), icon: '' },
  { name: '阿塞拜疆', flag: '🇦🇿', regex: new RegExp('🇦🇿|阿塞拜疆|azerbaijan', 'i'), icon: '' },
  { name: '巴林', flag: '🇧🇭', regex: new RegExp('🇧🇭|巴林|bahrain', 'i'), icon: '' },
  { name: '孟加拉国', flag: '🇧🇩', regex: new RegExp('🇧🇩|孟加拉国|bangladesh', 'i'), icon: '' },
  { name: '不丹', flag: '🇧🇹', regex: new RegExp('🇧🇹|不丹|bhutan', 'i'), icon: '' },
  { name: '格鲁吉亚', flag: '🇬🇪', regex: new RegExp('🇬🇪|格鲁吉亚|georgia', 'i'), icon: '' },
  { name: '伊朗', flag: '🇮🇷', regex: new RegExp('🇮🇷|伊朗|iran', 'i'), icon: '' },
  { name: '伊拉克', flag: '🇮🇶', regex: new RegExp('🇮🇶|伊拉克|iraq', 'i'), icon: '' },
  { name: '以色列', flag: '🇮🇱', regex: new RegExp('🇮🇱|以色列|israel', 'i'), icon: '' },
  { name: '约旦', flag: '🇯🇴', regex: new RegExp('🇯🇴|约旦|jordan', 'i'), icon: '' },
  { name: '哈萨克斯坦', flag: '🇰🇿', regex: new RegExp('🇰🇿|哈萨克斯坦|kazakhstan', 'i'), icon: '' },
  { name: '科威特', flag: '🇰🇼', regex: new RegExp('🇰🇼|科威特|kuwait', 'i'), icon: '' },
  { name: '吉尔吉斯斯坦', flag: '🇰🇬', regex: new RegExp('🇰🇬|吉尔吉斯斯坦|kyrgyzstan', 'i'), icon: '' },
  { name: '黎巴嫩', flag: '🇱🇧', regex: new RegExp('🇱🇧|黎巴嫩|lebanon', 'i'), icon: '' },
  { name: '马尔代夫', flag: '🇲🇻', regex: new RegExp('🇲🇻|马尔代夫|maldives', 'i'), icon: '' },
  { name: '蒙古', flag: '🇲🇳', regex: new RegExp('🇲🇳|蒙古|mongolia', 'i'), icon: '' },
  { name: '尼泊尔', flag: '🇳🇵', regex: new RegExp('🇳🇵|尼泊尔|nepal', 'i'), icon: '' },
  { name: '朝鲜', flag: '🇰🇵', regex: new RegExp('🇰🇵|朝鲜|north[\\s_-]*korea|dprk', 'i'), icon: '' },
  { name: '阿曼', flag: '🇴🇲', regex: new RegExp('🇴🇲|阿曼|oman', 'i'), icon: '' },
  { name: '巴基斯坦', flag: '🇵🇰', regex: new RegExp('🇵🇰|巴基斯坦|pakistan', 'i'), icon: '' },
  { name: '巴勒斯坦', flag: '🇵🇸', regex: new RegExp('🇵🇸|巴勒斯坦|palestine|west[\\s_-]*bank|gaza', 'i'), icon: '' },
  { name: '卡塔尔', flag: '🇶🇦', regex: new RegExp('🇶🇦|卡塔尔|qatar', 'i'), icon: '' },
  { name: '斯里兰卡', flag: '🇱🇰', regex: new RegExp('🇱🇰|斯里兰卡|sri[\\s_-]*lanka', 'i'), icon: '' },
  { name: '叙利亚', flag: '🇸🇾', regex: new RegExp('🇸🇾|叙利亚|syria', 'i'), icon: '' },
  { name: '塔吉克斯坦', flag: '🇹🇯', regex: new RegExp('🇹🇯|塔吉克斯坦|tajikistan', 'i'), icon: '' },
  { name: '东帝汶', flag: '🇹🇱', regex: new RegExp('🇹🇱|东帝汶|timor[\\s_-]*leste|east[\\s_-]*timor', 'i'), icon: '' },
  { name: '土库曼斯坦', flag: '🇹🇲', regex: new RegExp('🇹🇲|土库曼斯坦|turkmenistan', 'i'), icon: '' },
  {
    name: '阿联酋',
    flag: '🇦🇪',
    regex: new RegExp('🇦🇪|阿联酋|迪拜|阿布扎比|dubai|abu[\s_-]*dhabi|uae|united[\\s_-]*arab[\\s_-]*emirates', 'i'),
    icon: '',
  },
  { name: '乌兹别克斯坦', flag: '🇺🇿', regex: new RegExp('🇺🇿|乌兹别克斯坦|uzbekistan', 'i'), icon: '' },
  { name: '也门', flag: '🇾🇪', regex: new RegExp('🇾🇪|也门|yemen', 'i'), icon: '' },
  { name: '澳门', flag: '🇲🇴', regex: new RegExp('🇲🇴|澳门|macau|macao', 'i'), icon: '' },
  { name: '阿尔巴尼亚', flag: '🇦🇱', regex: new RegExp('🇦🇱|阿尔巴尼亚|albania', 'i'), icon: '' },
  { name: '安道尔', flag: '🇦🇩', regex: new RegExp('🇦🇩|安道尔|andorra', 'i'), icon: '' },
  { name: '白俄罗斯', flag: '🇧🇾', regex: new RegExp('🇧🇾|白俄罗斯|belarus', 'i'), icon: '' },
  {
    name: '波斯尼亚和黑塞哥维那',
    flag: '🇧🇦',
    regex: new RegExp('🇧🇦|波斯尼亚和黑塞哥维那|bosnia|bosnia[\\s_-]*and[\\s_-]*herzegovina', 'i'),
    icon: '',
  },
  { name: '冰岛', flag: '🇮🇸', regex: new RegExp('🇮🇸|冰岛|iceland', 'i'), icon: '' },
  { name: '列支敦士登', flag: '🇱🇮', regex: new RegExp('🇱🇮|列支敦士登|liechtenstein', 'i'), icon: '' },
  { name: '摩尔多瓦', flag: '🇲🇩', regex: new RegExp('🇲🇩|摩尔多瓦|moldova', 'i'), icon: '' },
  { name: '摩纳哥', flag: '🇲🇨', regex: new RegExp('🇲🇨|摩纳哥|monaco', 'i'), icon: '' },
  { name: '黑山', flag: '🇲🇪', regex: new RegExp('🇲🇪|黑山|montenegro', 'i'), icon: '' },
  { name: '北马其顿', flag: '🇲🇰', regex: new RegExp('🇲🇰|北马其顿|north[\\s_-]*macedonia|macedonia', 'i'), icon: '' },
  { name: '挪威', flag: '🇳🇴', regex: new RegExp('🇳🇴|挪威|norway', 'i'), icon: '' },
  { name: '圣马力诺', flag: '🇸🇲', regex: new RegExp('🇸🇲|圣马力诺|san[\\s_-]*marino', 'i'), icon: '' },
  { name: '塞尔维亚', flag: '🇷🇸', regex: new RegExp('🇷🇸|塞尔维亚|serbia', 'i'), icon: '' },
  { name: '瑞士', flag: '🇨🇭', regex: new RegExp('🇨🇭|瑞士|switzerland', 'i'), icon: '' },
  { name: '乌克兰', flag: '🇺🇦', regex: new RegExp('🇺🇦|乌克兰|ukraine', 'i'), icon: '' },
  { name: '梵蒂冈', flag: '🇻🇦', regex: new RegExp('🇻🇦|梵蒂冈|vatican', 'i'), icon: '' },
  { name: '科索沃', flag: '🇽🇰', regex: new RegExp('🇽🇰|科索沃|kosovo', 'i'), icon: '' },
  { name: '巴哈马', flag: '🇧🇸', regex: new RegExp('🇧🇸|巴哈马|bahamas', 'i'), icon: '' },
  { name: '巴巴多斯', flag: '🇧🇧', regex: new RegExp('🇧🇧|巴巴多斯|barbados', 'i'), icon: '' },
  { name: '伯利兹', flag: '🇧🇿', regex: new RegExp('🇧🇿|伯利兹|belize', 'i'), icon: '' },
  { name: '哥斯达黎加', flag: '🇨🇷', regex: new RegExp('🇨🇷|哥斯达黎加|costa[\\s_-]*rica', 'i'), icon: '' },
  { name: '古巴', flag: '🇨🇺', regex: new RegExp('🇨🇺|古巴|cuba', 'i'), icon: '' },
  { name: '多米尼克', flag: '🇩🇲', regex: new RegExp('🇩🇲|多米尼克|dominica', 'i'), icon: '' },
  { name: '多米尼加', flag: '🇩🇴', regex: new RegExp('🇩🇴|多米尼加|dominican[\\s_-]*republic|dominican', 'i'), icon: '' },
  { name: '萨尔瓦多', flag: '🇸🇻', regex: new RegExp('🇸🇻|萨尔瓦多|el[\\s_-]*salvador', 'i'), icon: '' },
  { name: '格林纳达', flag: '🇬🇩', regex: new RegExp('🇬🇩|格林纳达|grenada', 'i'), icon: '' },
  { name: '危地马拉', flag: '🇬🇹', regex: new RegExp('🇬🇹|危地马拉|guatemala', 'i'), icon: '' },
  { name: '海地', flag: '🇭🇹', regex: new RegExp('🇭🇹|海地|haiti', 'i'), icon: '' },
  { name: '洪都拉斯', flag: '🇭🇳', regex: new RegExp('🇭🇳|洪都拉斯|honduras', 'i'), icon: '' },
  { name: '牙买加', flag: '🇯🇲', regex: new RegExp('🇯🇲|牙买加|jamaica', 'i'), icon: '' },
  { name: '尼加拉瓜', flag: '🇳🇮', regex: new RegExp('🇳🇮|尼加拉瓜|nicaragua', 'i'), icon: '' },
  { name: '巴拿马', flag: '🇵🇦', regex: new RegExp('🇵🇦|巴拿马|panama', 'i'), icon: '' },
  {
    name: '圣基茨和尼维斯',
    flag: '🇰🇳',
    regex: new RegExp('🇰🇳|圣基茨和尼维斯|saint[\\s_-]*kitts|st[\\s_-]*kitts', 'i'),
    icon: '',
  },
  { name: '圣卢西亚', flag: '🇱🇨', regex: new RegExp('🇱🇨|圣卢西亚|saint[\\s_-]*lucia|st[\\s_-]*lucia', 'i'), icon: '' },
  {
    name: '圣文森特和格林纳丁斯',
    flag: '🇻🇨',
    regex: new RegExp('🇻🇨|圣文森特和格林纳丁斯|saint[\\s_-]*vincent|st[\\s_-]*vincent', 'i'),
    icon: '',
  },
  {
    name: '特立尼达和多巴哥',
    flag: '🇹🇹',
    regex: new RegExp('🇹🇹|特立尼达和多巴哥|trinidad[\\s_-]*and[\\s_-]*tobago', 'i'),
    icon: '',
  },
  {
    name: '安提瓜和巴布达',
    flag: '🇦🇬',
    regex: new RegExp('🇦🇬|安提瓜和巴布达|antigua[\\s_-]*and[\\s_-]*barbuda', 'i'),
    icon: '',
  },
  {
    name: '哥伦比亚',
    flag: '🇨🇴',
    regex: new RegExp('🇨🇴|哥伦比亚|波哥大|麦德林|(?:^|[^A-Za-z])CO(?:$|[^A-Za-z])|bogot[aá]|medellin|colombia', 'i'),
    icon: '',
  },
  { name: '智利', flag: '🇨🇱', regex: new RegExp('🇨🇱|智利|chile', 'i'), icon: '' },
  { name: '秘鲁', flag: '🇵🇪', regex: new RegExp('🇵🇪|秘鲁|peru', 'i'), icon: '' },
  { name: '乌拉圭', flag: '🇺🇾', regex: new RegExp('🇺🇾|乌拉圭|uruguay', 'i'), icon: '' },
  { name: '巴拉圭', flag: '🇵🇾', regex: new RegExp('🇵🇾|巴拉圭|paraguay', 'i'), icon: '' },
  { name: '玻利维亚', flag: '🇧🇴', regex: new RegExp('🇧🇴|玻利维亚|bolivia', 'i'), icon: '' },
  { name: '厄瓜多尔', flag: '🇪🇨', regex: new RegExp('🇪🇨|厄瓜多尔|ecuador', 'i'), icon: '' },
  { name: '委内瑞拉', flag: '🇻🇪', regex: new RegExp('🇻🇪|委内瑞拉|venezuela', 'i'), icon: '' },
  { name: '圭亚那', flag: '🇬🇾', regex: new RegExp('🇬🇾|圭亚那|guyana', 'i'), icon: '' },
  { name: '苏里南', flag: '🇸🇷', regex: new RegExp('🇸🇷|苏里南|suriname', 'i'), icon: '' },
  {
    name: '新西兰',
    flag: '🇳🇿',
    regex: new RegExp('🇳🇿|新西兰|new[\\s_-]*zealand|auckland|奥克兰|wellington|惠灵顿', 'i'),
    icon: '',
  },
  { name: '斐济', flag: '🇫🇯', regex: new RegExp('🇫🇯|斐济|fiji', 'i'), icon: '' },
  {
    name: '巴布亚新几内亚',
    flag: '🇵🇬',
    regex: new RegExp('🇵🇬|巴布亚新几内亚|papua[\\s_-]*new[\\s_-]*guinea', 'i'),
    icon: '',
  },
  { name: '所罗门群岛', flag: '🇸🇧', regex: new RegExp('🇸🇧|所罗门群岛|solomon[\\s_-]*islands', 'i'), icon: '' },
  { name: '瓦努阿图', flag: '🇻🇺', regex: new RegExp('🇻🇺|瓦努阿图|vanuatu', 'i'), icon: '' },
  { name: '萨摩亚', flag: '🇼🇸', regex: new RegExp('🇼🇸|萨摩亚|samoa', 'i'), icon: '' },
  { name: '汤加', flag: '🇹🇴', regex: new RegExp('🇹🇴|汤加|tonga', 'i'), icon: '' },
  { name: '基里巴斯', flag: '🇰🇮', regex: new RegExp('🇰🇮|基里巴斯|kiribati', 'i'), icon: '' },
  { name: '图瓦卢', flag: '🇹🇻', regex: new RegExp('🇹🇻|图瓦卢|tuvalu', 'i'), icon: '' },
  { name: '瑙鲁', flag: '🇳🇷', regex: new RegExp('🇳🇷|瑙鲁|nauru', 'i'), icon: '' },
  { name: '帕劳', flag: '🇵🇼', regex: new RegExp('🇵🇼|帕劳|palau', 'i'), icon: '' },
  { name: '马绍尔群岛', flag: '🇲🇭', regex: new RegExp('🇲🇭|马绍尔群岛|marshall[\\s_-]*islands', 'i'), icon: '' },
  {
    name: '密克罗尼西亚',
    flag: '🇫🇲',
    regex: new RegExp('🇫🇲|密克罗尼西亚|micronesia|federated[\\s_-]*states[\\s_-]*of[\\s_-]*micronesia', 'i'),
    icon: '',
  },
  { name: '关岛', flag: '🇬🇺', regex: new RegExp('🇬🇺|关岛|guam', 'i'), icon: '' },
  { name: '波多黎各', flag: '🇵🇷', regex: new RegExp('🇵🇷|波多黎各|puerto[\\s_-]*rico', 'i'), icon: '' },
  { name: '百慕大', flag: '🇧🇲', regex: new RegExp('🇧🇲|百慕大|bermuda', 'i'), icon: '' },
  { name: '格陵兰', flag: '🇬🇱', regex: new RegExp('🇬🇱|格陵兰|greenland', 'i'), icon: '' },
  { name: '库拉索', flag: '🇨🇼', regex: new RegExp('🇨🇼|库拉索|curacao|curaçao', 'i'), icon: '' },
  { name: '阿鲁巴', flag: '🇦🇼', regex: new RegExp('🇦🇼|阿鲁巴|aruba', 'i'), icon: '' },
  { name: '开曼群岛', flag: '🇰🇾', regex: new RegExp('🇰🇾|开曼群岛|cayman[\\s_-]*islands', 'i'), icon: '' },
  {
    name: '英属维尔京群岛',
    flag: '🇻🇬',
    regex: new RegExp('🇻🇬|英属维尔京群岛|british[\\s_-]*virgin[\\s_-]*islands', 'i'),
    icon: '',
  },
  {
    name: '美属维尔京群岛',
    flag: '🇻🇮',
    regex: new RegExp('🇻🇮|美属维尔京群岛|us[\\s_-]*virgin[\\s_-]*islands|u\\.s\\.[\\s_-]*virgin[\\s_-]*islands', 'i'),
    icon: '',
  },
  { name: '新喀里多尼亚', flag: '🇳🇨', regex: new RegExp('🇳🇨|新喀里多尼亚|new[\\s_-]*caledonia', 'i'), icon: '' },
  { name: '法属波利尼西亚', flag: '🇵🇫', regex: new RegExp('🇵🇫|法属波利尼西亚|french[\\s_-]*polynesia', 'i'), icon: '' },
  { name: '库克群岛', flag: '🇨🇰', regex: new RegExp('🇨🇰|库克群岛|cook[\\s_-]*islands', 'i'), icon: '' },
  { name: '纽埃', flag: '🇳🇺', regex: new RegExp('🇳🇺|纽埃|niue', 'i'), icon: '' },
];
